// dataset 
const BaseDatasets = {
    'indicators' : [
        { "model": "backoffice.SisMeasure", "pk": "active_carbonate", "fields": { "code":"active_carbonate", "name":"Active carbonate (CaCo3)", "abstract": "Finest and most reactive CaCO3 fractions, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}},        
        { "model": "backoffice.SisMeasure", "pk": "antimony", "fields": { "code":"antimony", "name":"Antimony (Sb)", "abstract": "Antimony content, mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "arsenic", "fields": { "code":"arsenic", "name":"Arsenic (As)", "abstract": "Arsenic content, mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "available_p_content", "fields": { "code":"available_p_content", "name":"Available Phosphorus (P) content", "abstract": "Available Phosphorus (P) content, mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "base_saturation_exchangeable_activity", "fields": { "code":"base_saturation_exchangeable_activity", "name":"Available Base Saturation (BS) exchangeable activity", "abstract": "Available base saturation (BS) exchangeable activity, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "base_saturation_soil_structure", "fields": { "code":"base_saturation_soil_structure", "name":"Base Saturation (BS) soil structure", "abstract": "base saturation (BS) soil structure, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "bulk_density", "fields": { "code":"bulk_density", "name":"Bulk Density (BD)", "abstract": "Mass of dry soil per unit total volume (considering pore volume) impacting root growth differently in function of the soil texture", "unit": "MEASURE_UNITS:g/cm3", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "cadmium", "fields": { "code":"cadmium", "name":"Cadmium (Cd)", "abstract": "Cadmium content, mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}}, 
        { "model": "backoffice.SisMeasure", "pk": "carbonate_content", "fields": { "code":"carbonate_content", "name":"Carbonates content", "abstract": "Carbonates (e.g. CaCO3, MgCO3) content, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}}, 
        { "model": "backoffice.SisMeasure", "pk": "cation_exchange_capacity","fields": { "code":"cation_exchange_capacity", "name":"Cation Exchange Capacity (CEC)", "abstract": "CCation Exchange Capacity at buffered pH, cmol/kg", "unit": "MEASURE_UNITS:cmol/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "cec_clay_ratio", "fields": { "code":"cec_clay_ratio", "name":"Cation Exchange Capacity (CEC) / Clay ratio", "abstract": "Indicator of low or high charge density clays (including swelling clays) (Stewart & Hossner, 2001), unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "chromium", "fields": { "code":"chromium", "name":"Chromium (Cr)", "abstract": "Chromium (Cr) content, mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "cobalt", "fields": { "code":"cobalt", "name":"Cobalt (Co)", "abstract": "Cobalt (Co) content, mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "copper", "fields": { "code":"copper", "name":"Copper (Cu)", "abstract": "Copper (Cu) content, mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "copper_relative_content", "fields": { "code":"copper_relative_content", "name":"Copper (Cu) Relative Content", "abstract": "Copper (Cu) Relative Content, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "crust_cover", "fields": { "code":"crust_cover", "name":"Crust Cover", "abstract": "Crust Cover, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "cryptogram_cover", "fields": { "code":"cryptogram_cover", "name":"Cryptogram Cover", "abstract": "Cryptogram Cover, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "c_n_ratio", "fields": { "code":"c_n_ratio", "name":"C/N ratio", "abstract": "C/N ratio, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "biological_health"}},
        { "model": "backoffice.SisMeasure", "pk": "effective_cation_exchange_capacity", "fields": { "code":"effective_cation_exchange_capacity", "name":"Effective Cation Exchange Capacity (ECEC)", "abstract": "Effective Cation Exchange Capacity (ECEC), percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "electric_conductivity", "fields": { "code":"electric_conductivity", "name":"Electric Conductivity (EC)", "abstract": "Electric Conductivity (EC), dS/m", "unit": "MEASURE_UNITS:dS/m", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "exchangeable_calcium", "fields": { "code":"exchangeable_calcium", "name":"Exchangeable Calcium (Ca+)", "abstract": "Exchangeable Calcium (Ca+), cmol/kg", "unit": "MEASURE_UNITS:cmol/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "exchangeable_magnesium", "fields": { "code":"exchangeable_magnesium", "name":"Exchangeable Magnesium (Mg++)", "abstract": "Exchangeable Magnesium (Mg++), cmol/kg", "unit": "MEASURE_UNITS:cmol/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "exchangeable_potassium", "fields": { "code":"exchangeable_potassium", "name":"Exchangeable Potassium (K+)", "abstract": "Exchangeable Potassium (K+) cation, cmol/kg", "unit": "MEASURE_UNITS:cmol/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "exchangeable_potassium_potential_impact", "fields": { "code":"exchangeable_potassium_potential_impact", "name":"Exchangeable Potassium (K+) cation, potential impact on production", "abstract": "Exchangeable Potassium (K+) potential impact on production, cmol/kg", "unit": "MEASURE_UNITS:cmol/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "exchangeable_sodium", "fields": { "code":"exchangeable_sodium", "name":"Exchangeable Sodium (Na+)", "abstract": "Exchangeable Sodium (Na+) cation, cmol/kg", "unit": "MEASURE_UNITS:cmol/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "field_capacity", "fields": { "code":"field_capacity", "name":"field capacity", "abstract": "Volumetric water content remaining in the soil after gravitational drainage has become negligible; the interpretation takes soil texture into account., percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "gravel", "fields": { "code":"gravel", "name":"gravel", "abstract": "gravel, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "gypsum", "fields": { "code":"gypsum", "name":"gypsum", "abstract": "gypsum, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "hydraulic_conductivity_at_saturation", "fields": { "code":"hydraulic_conductivity_at_saturation", "name":"Hydraulic conductivity at saturation", "abstract": "Hydraulic conductivity at saturation, ds/m", "unit": "MEASURE_UNITS:ds/m", "keywords": "chemical_health"}},      
        { "model": "backoffice.SisMeasure", "pk": "lead", "fields": { "code":"lead", "name":"Lead (Pb) mg/kg", "abstract": "Lead (Pb) content, mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "lead_relative_content", "fields": { "code":"lead_relative_content", "name":"Lead relative content, percentage", "abstract": "Lead relative content, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "litter_layer_cover", "fields": { "code":"litter_layer_cover", "name":"Litter Layer cover", "abstract": "Litter layer cover, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "manganese", "fields": { "code":"manganese", "name":"Manganese (Mn)", "abstract": "Manganese (Mn) content, mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "mercury", "fields": { "code":"mercury", "name":"Mercury (Hg)", "abstract": "Mercury (Hg) content, mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "n_total", "fields": { "code":"n_total", "name":"Total Soil Nitrogen (N)", "abstract": "Total Soil Nitrogen (N), g/kg", "unit": "MEASURE_UNITS:g/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "nh4", "fields": { "code":"nh4", "name":"Ammonium ion (NH4+)", "abstract": "Ammonium ion (NH4+), mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "nichel", "fields": { "code":"nichel", "name":"Nichel (Ni)", "abstract": "Nichel (Ni), mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "no3", "fields": { "code":"no3", "name":"Nitrate ion (NO3-)", "abstract": "Nitrate ion (NO3-), mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "organic_carbon", "fields": { "code":"organic_carbon", "name":"Organic Carbon (SOC)", "abstract": "Organic Carbon content, g/kg", "unit": "MEASURE_UNITS:g/kg", "keywords": "biological_health"}},
        { "model": "backoffice.SisMeasure", "pk": "organic_matter", "fields": { "code":"organic_matter", "name":"Organic Matter", "abstract": "Organic Matter content, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "biological_health"}},
        { "model": "backoffice.SisMeasure", "pk": "oxygen_availability_for_roots", "fields": { "code":"oxygen_availability_for_roots", "name":"Oxygen availability for roots", "abstract": "Oxygen availability for roots, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "p_p_threshold", "fields": { "code":"p_p_threshold", "name":"Phosphorus Threshold for Plant growth", "abstract": "Phosphorus Threshold for Plant growth, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "packing_density", "fields": { "code":"packing_density", "name":"Packing density", "abstract": "Measure of soil compaction considering the volume occupied by solid material, excluding pore space (Panagos et al., 2024), g/cm3", "unit": "MEASURE_UNITS:g/cm3", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "perennial_vegetation_cover", "fields": { "code":"perennial_vegetation_cover", "name":"Perennial vegetation cover", "abstract": "Perennial vegetation cover, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "biological_health"}},
        { "model": "backoffice.SisMeasure", "pk": "ph_h2o_bacterial_diversity", "fields": { "code":"ph_h2o_bacterial_diversity", "name":"pH-H2O bacterial diversity", "abstract": "pH (H2O) related to bacterial diversity, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},    
        { "model": "backoffice.SisMeasure", "pk": "ph_h2o_fungal", "fields": { "code":"ph_h2o_fungal", "name":"pH-H2O fungal activity", "abstract": "pH (H2O) related to fungal activity, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "ph_h2o_metal_toxicity", "fields": { "code":"ph_h2o_metal_toxicity", "name":"pH-H2O metal toxicity", "abstract": "pH (H2O) related to toxicity of heavy metals dissolution, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "ph_h2o_microbial_carbon", "fields": { "code":"ph_h2o_microbial_carbon", "name":"pH-H2O microbial carbon", "abstract": "pH (H2O) related to microbial carbon use efficiency, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "ph_h2o_microbial_diversity", "fields": { "code":"ph_h2o_microbial_diversity", "name":"pH-H2O microbial diversity", "abstract": "pH (H2O) related to microbial diversity, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "ph_h2o_organic_decomposition", "fields": { "code":"ph_h2o_organic_decomposition", "name":"pH-H2O organic decomposition, unitless", "abstract": "pH (H2O) related to organic matter decomposition,unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "ph_h2o_phosphorus", "fields": { "code":"ph_h2o_phosphorus", "name":"pH-H2O phosphorus", "abstract": "pH (H2O) related to phosphorus availability with acid phosphorus enzyme activity, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "ph_h2o_plant_growth", "fields": { "code":"ph_h2o_plant_growth", "name":"pH-H2O plant growth", "abstract": "pH (H2O) related to the optimal plant growth, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "ph_h2o_soil_salinity", "fields": { "code":"ph_h2o_soil_salinity", "name":"pH-H2O soil salinity", "abstract": "pH (H2O) related to soil salinity and structural deterioration, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "ph_h2o_som_for_grassland", "fields": { "code":"ph_h2o_som_for_grassland", "name":"pH-H2O som for grassland", "abstract": "pH (H2O) related to redistribution of SOM for bioturbation by earthworm activity in grassland, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "plant_available_water_capacity", "fields": { "code":"plant_available_water_capacity", "name":"Plant Available Water Capacity (PAWC)", "abstract": "Soil's ability to store and provide water available to plant roots, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "relative_field_capacity", "fields": { "code":"relative_field_capacity", "name":"Relative field capacity", "abstract": "Soil's ability to provide an optimal balance between water and air within the total pore volume (Di Prima et al., 2024), unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "slake_test", "fields": { "code":"slake_test", "name":"Slake test", "abstract": "Aggregate stability index after 10 minutes immersed in water (STAB10), unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "soc_stock", "fields": { "code":"soc_stock", "name":"SOC stock", "abstract": "SOC stock, mg.ha^-1", "unit": "MEASURE_UNITS:", "keywords": "biological_health"}},
        { "model": "backoffice.SisMeasure", "pk": "sodicity_salinity_ratio", "fields": { "code":"sodicity_salinity_ratio", "name":"Sodicity Salinity Ratio", "abstract": "Indicator of potential salinity and sodification remediation by gypsum input, without permeability, pH or EC being unbalance; It can be calculated 1) only for topsoil layer,  if 2) electrical conductivity is between 0.2 and 20 dS m-1 and if 3) and if soluble cations and conductivity are measured in saturated paste extract, unitless", "unit": "MEASURE_UNITS:unitless", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "sodium_adsorption_ratio_sodicity", "fields": { "code":"sodium_adsorption_ratio_sodicity", "name":"Sodium Adsorption Ratio (SAR) sodicity", "abstract": "Sodicity indicator defined as the proportion of soluble sodium divided by the square root of the sum of soluble calcium and magnesium concentrations measured in saturated paste extracts (Ali, 2011) cmol(c)^(1/2).L^(-1/2)", "unit": "MEASURE_UNITS:cmol(c)^(1/2).L^(-1/2)", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "sodium_adsorption_ratio_toxicity", "fields": { "code":"sodium_adsorption_ratio_toxicity", "name":"Sodium Adsorption Ratio (SAR) toxicity", "abstract": "Sodicity indicator on toxicity for the cultivation of sensitive crops in rainfed crop system only (e.g. agrum trees), cmol(c)^(1/2).L^(-1/2)", "unit": "MEASURE_UNITS:cmol(c)^(1/2).L^(-1/2)", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "sodium_exchangeable_percentage_sodicity", "fields": { "code":"sodium_exchangeable_percentage_sodicity", "name":"Sodium Exchangeable Percentage (SEP) sodicity", "abstract": "Sodicity indicator based on exchangeable sodium and cation exchange capacity (CEC) (Ali, 2011), percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "sodium_exchangeable_percentage_waterlogging", "fields": { "code":"sodium_exchangeable_percentage_waterlogging", "name":"Sodium Exchangeable Percentage (SEP) waterlogging", "abstract": "Waterlogging indicator based on exchangeable sodium and cation exchange capacity (CEC) (Ali, 2011), percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "soil_erodibility_by_water", "fields": { "code":"soil_erodibility_by_water", "name":"Soil Erodibility by Water", "abstract": "Indicator of the soil erosion potential based on texture, OM content, soil structure (s) and permeability (p) (Renard et al., 1977, p.74), Mg.h.MJ^-1.mm^-1", "unit": "MEASURE_UNITS:Mg.h.MJ^(-1).mm^(-1)", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "soil_erodibility_by_wind", "fields": { "code":"soil_erodibility_by_wind", "name":"Soil Erodibility by Wind", "abstract": "Soil Erodibility by Wind, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "surface_compaction_risk", "fields": { "code":"surface_compaction_risk", "name":"Surface Compaction Risk", "abstract": "Indicator of potential soil compaction sensitivity, applicable to topsoil only (Costantini, 2007), kg.m^-2", "unit": "MEASURE_UNITS:kg.m^-2", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "total_iron", "fields": { "code":"total_iron", "name":"Total Iron (Fe)", "abstract": "Total Iron (Fe), mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "vanadium", "fields": { "code":"vanadium", "name":"Vanadium (V)", "abstract": "Vanadium (V), mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "wilting_point", "fields": { "code":"wilting_point", "name":"Wilting Point", "abstract": "Volumetric water content at which plants can no longer extract water, resulting in irreversible wilting. percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "physical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "zinc", "fields": { "code":"zinc", "name":"Zinc (Z)", "abstract": "Zinc (Z), mg/kg", "unit": "MEASURE_UNITS:mg/kg", "keywords": "chemical_health"}},
        { "model": "backoffice.SisMeasure", "pk": "zinc_relative_content", "fields": { "code":"zinc_relative_content", "name":"Zinc (Z) Relative Content", "abstract": "Zinc (Z) Relative Content, percentage", "unit": "MEASURE_UNITS:percentage", "keywords": "chemical_health"}}, 
    ],
    'aoiSoilIndicators': [
        { name:"Enrichment factor - Pb", typename:"labdata_geo",  },
        { name:"Enrichment factor - Hg", typename:"labdata_geo"  },
        { name:"Enrichment factor - Cd", typename:"labdata_geo"  },
        { name:"Enrichment factor - Ni", typename:"labdata_geo"  },
        { name:"Enrichment factor - Cu", typename:"labdata_geo"  },
        { name:"Enrichment factor - Sb", typename:"labdata_geo"  },
        { name:"Enrichment factor - Mn", typename:"labdata_geo"  },
        { name:"Enrichment factor - Cr", typename:"labdata_geo"  },
        { name:"Enrichment factor - Co", typename:"labdata_geo"  },
        { name:"Enrichment factor - V", typename:"labdata_geo"  },
        { name:"Enrichment factor - As", typename:"labdata_geo"  },
    ],
    'sections' : [
        { name:"point general data", typename:"point_general_geo"  },
        { name:"surface unevenness data", typename:"surface_unevenness_geo"},
        { name:"surface general", typename:"surface_geo"},
        { name:"surface land use", typename:"land_use_geo"},
        { name:"climate and weather", typename:"climate_weather_geo"},
        { name:"landform and topography", typename:"landform_topography_geo"},
        { name:"layer general data", typename:"point_layer_geo"},
        { name:"layer remants data", typename:"layer_remants_geo"}, 
        { name:"layer coarse fragments data", typename:"layer_coarse_fragments_geo"},
        { name:"layer artefacts data", typename:"layer_artefacts_geo"},
        { name:"layer cracks data", typename:"layer_cracks_geo"},
        { name:"layer matrix colours data", typename:"layer_matrix_colours_geo"},
        { name:"layer lithogenic variegates data", typename:"layer_lithogenic_variegates_geo"},
        { name:"Layer redoximorphic features ", typename:"layer_redoximorphic_geo"}, 
        { name:"Layer coatings bridges data", typename:"layer_coatings_bridges_geo"}, 
        { name:"Layer carbonates data", typename:"layer_carbonates_geo"},
        { name:"Layer gypsum data", typename:"layer_gypsum_geo"},
        { name:"Layer secondary silica data", typename:"layer_secondary_silica_geo"}, 
        { name:"Layer consistence data", typename:"layer_consistence_geo"},
        { name:"layer permafrost data", typename:"layer_permafrost_geo"},
        { name:"Layer organic carbon data", typename:"layer_organic_carbon_geo"},
        { name:"Layer roots data", typename:"layer_roots_geo"},
        { name:"Layer animal activity data", typename:"layer_animal_activity_geo"},
        { name:"Layer human alterations data", typename:"layer_human_alterations_geo"},
        { name:"Layer degree of decomposition data", typename:"layer_degree_decomposition_geo"},
        { name:"Layer nomatrix pore data", typename:"layer_nonmatrix_pore_geo"},
        { name:"Layer structure data", typename:"layer_structure_geo"},
        { name:"Extra laboratory measure data", typename:"labdata_extra_geo"},
        { name:"laboratory data", typename:"labdata_geo"},
    ]
}

export default BaseDatasets
