<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<NamedLayer>
    	<Name>Bulk density (g/cm3)</Name>
    	<UserStyle>
			<Name>Bulk density (g/cm3)</Name>
			<Title>Bulk density (g/cm3)</Title>
			<FeatureTypeStyle>
      			<Rule>
         			<Name>Suitable for plant growth</Name>
         			<Filter xmlns="http://www.opengis.net/ogc"> 
						<Or>
							<!-- Primo blocco AND -->
							<And>  
		       					<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>S</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>LS</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>0</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.6</Literal>
								</PropertyIsLessThan>
							</And>
							<!-- Secondo blocco AND -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SL</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>L</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>0</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.4</Literal>
								</PropertyIsLessThan>
							</And>
							<!-- Terzo blocco AND -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SCL</Literal>
									</ogc:PropertyIsEqualTo>
									<And>
										<ogc:PropertyIsEqualTo>
											<ogc:PropertyName>texture</ogc:PropertyName>
											<Literal>CL</Literal>
										</ogc:PropertyIsEqualTo>
										<PropertyIsGreaterThanOrEqualTo>
											<PropertyName>clay</PropertyName>
											<Literal>27</Literal>
										</PropertyIsGreaterThanOrEqualTo>
										<PropertyIsLessThan>
											<PropertyName>clay</PropertyName>
											<Literal>35</Literal>
										</PropertyIsLessThan>
									</And>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>0</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.4</Literal>
									</PropertyIsLessThan>
							</And>
							<!-- Quarto blocco AND -->
    						<And>  
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>texture</ogc:PropertyName>
									<Literal>Si</Literal>
								</ogc:PropertyIsEqualTo>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>0</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.4</Literal>
								</PropertyIsLessThan>
							</And>
							<!-- Quinto blocco AND -->
    						<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SiL</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SiCL</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>0</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.4</Literal>
								</PropertyIsLessThan>
							</And>
							<!-- Sesto blocco AND -->
    						<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SC</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SiC</Literal>
									</ogc:PropertyIsEqualTo>
									<And>
										<ogc:PropertyIsEqualTo>
											<ogc:PropertyName>texture</ogc:PropertyName>
											<Literal>C</Literal>
										</ogc:PropertyIsEqualTo>
										<PropertyIsGreaterThanOrEqualTo>
											<PropertyName>clay</PropertyName>
											<Literal>45</Literal>
										</PropertyIsGreaterThanOrEqualTo>
									</And>
			 						<And>
										<ogc:PropertyIsEqualTo>
											<ogc:PropertyName>texture</ogc:PropertyName>
											<Literal>CL</Literal>
										</ogc:PropertyIsEqualTo>
										<PropertyIsGreaterThanOrEqualTo>
											<PropertyName>clay</PropertyName>
											<Literal>35</Literal>
                	  					</PropertyIsGreaterThanOrEqualTo>
			 						</And>
		     					</Or>
		     					<PropertyIsGreaterThanOrEqualTo>
                					<PropertyName>value</PropertyName>
                					<Literal>0</Literal>
              					</PropertyIsGreaterThanOrEqualTo>
             		      		<PropertyIsLessThan>
                		        	<PropertyName>value</PropertyName>
                					<Literal>1.3</Literal>
             		      		</PropertyIsLessThan>
							</And>
						</Or>
					</Filter>
          			<PointSymbolizer>
						<Graphic>
							<Mark>
								<WellKnownName>circle</WellKnownName>
								<Fill>
								<CssParameter name="fill">#41ED31</CssParameter>
								<CssParameter name="fill-opacity">1</CssParameter>
								</Fill>
								<Stroke>
								<CssParameter name="stroke">#777777</CssParameter>
								<CssParameter name="stroke-width">2</CssParameter>
								<CssParameter name="stroke-opacity">1</CssParameter>
								</Stroke>
							</Mark>
							<Size>14</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Medium</Name>
					<Filter xmlns="http://www.opengis.net/ogc">
          				<Or>
    					<!-- Primo blocco AND_2 -->
    						<And>  
		     					<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>S</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>LS</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
		     					<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.6</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
										<PropertyName>value</PropertyName>
									<Literal>1.69</Literal>
								</PropertyIsLessThan>
							</And>
							<!-- Secondo blocco AND_2 -->
    						<And>  
		     					<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SL</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>L</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
                					<PropertyName>value</PropertyName>
                					<Literal>1.4</Literal>
              					</PropertyIsGreaterThanOrEqualTo>
             		      		<PropertyIsLessThan>
                		        	<PropertyName>value</PropertyName>
                					<Literal>1.63</Literal>
             		      		</PropertyIsLessThan>
							</And>
							<!-- Terzo blocco AND_2 -->
    						<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SCL</Literal>
									</ogc:PropertyIsEqualTo>
									<And>
										<ogc:PropertyIsEqualTo>
											<ogc:PropertyName>texture</ogc:PropertyName>
											<Literal>CL</Literal>
										</ogc:PropertyIsEqualTo>
										<PropertyIsGreaterThanOrEqualTo>
											<PropertyName>clay</PropertyName>
                	  						<Literal>27</Literal>
              		  					</PropertyIsGreaterThanOrEqualTo>
										<PropertyIsLessThan>
											<PropertyName>clay</PropertyName>
											<Literal>35</Literal>
										</PropertyIsLessThan>
		        					</And>
		     					</Or>
		     					<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.4</Literal>
              					</PropertyIsGreaterThanOrEqualTo>
             		      		<PropertyIsLessThan>
                		        	<PropertyName>value</PropertyName>
                					<Literal>1.6</Literal>
             		      		</PropertyIsLessThan>
							</And>
							<!-- Quarto blocco AND_2 -->
							<And>  
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>texture</ogc:PropertyName>
									<Literal>Si</Literal>
								</ogc:PropertyIsEqualTo>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.4</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.6</Literal>
								</PropertyIsLessThan>
							</And>
							<!-- Quinto blocco AND_2 -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SiL</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SiCL</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.4</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.55</Literal>
								</PropertyIsLessThan>
							</And>
        				</Or>
        			</Filter>
					<PointSymbolizer>
						<Graphic>
							<Mark>
								<WellKnownName>circle</WellKnownName>
								<Fill>
									<CssParameter name="fill">#194012</CssParameter>
									<CssParameter name="fill-opacity">1</CssParameter>
								</Fill>
								<Stroke>
									<CssParameter name="stroke">#777777</CssParameter>
									<CssParameter name="stroke-width">2</CssParameter>
									<CssParameter name="stroke-opacity">1</CssParameter>
								</Stroke>
							</Mark>
							<Size>14</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Affect root growth</Name>
					<Filter xmlns="http://www.opengis.net/ogc">
						<Or>    
							<!-- Primo blocco AND_3 -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>S</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>LS</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.69</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.8</Literal>
								</PropertyIsLessThan>
							</And>
							<!-- Secondo blocco AND_3 -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SL</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>L</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.63</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.8</Literal>
								</PropertyIsLessThan>
							</And>
							<!-- Terzo blocco AND_3 -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SCL</Literal>
									</ogc:PropertyIsEqualTo>
									<And>
										<ogc:PropertyIsEqualTo>
											<ogc:PropertyName>texture</ogc:PropertyName>
											<Literal>CL</Literal>
										</ogc:PropertyIsEqualTo>
										<PropertyIsGreaterThanOrEqualTo>
											<PropertyName>clay</PropertyName>
											<Literal>27</Literal>
										</PropertyIsGreaterThanOrEqualTo>
										<PropertyIsLessThan>
											<PropertyName>clay</PropertyName>
											<Literal>35</Literal>
										</PropertyIsLessThan>
									</And>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.6</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.75</Literal>
								</PropertyIsLessThan>
							</And>
							<!-- Quarto blocco AND_3 -->
							<And>  
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>texture</ogc:PropertyName>
									<Literal>Si</Literal>
								</ogc:PropertyIsEqualTo>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.6</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.75</Literal>
								</PropertyIsLessThan>
							</And>
							<!-- Quinto blocco AND_3 -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SiL</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SiCL</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.55</Literal>
								</PropertyIsGreaterThanOrEqualTo>
								<PropertyIsLessThan>
									<PropertyName>value</PropertyName>
									<Literal>1.65</Literal>
								</PropertyIsLessThan>
							</And>
						</Or>
					</Filter>
					<PointSymbolizer>
						<Graphic>
							<Mark>
								<WellKnownName>circle</WellKnownName>
								<Fill>
									<CssParameter name="fill">#2649F7</CssParameter>
									<CssParameter name="fill-opacity">1</CssParameter>
								</Fill>
								<Stroke>
									<CssParameter name="stroke">#777777</CssParameter>
									<CssParameter name="stroke-width">2</CssParameter>
									<CssParameter name="stroke-opacity">1</CssParameter>
								</Stroke>
							</Mark>
							<Size>14</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>
				<Rule>
					<Name>Restrict root growth</Name>
					<Filter xmlns="http://www.opengis.net/ogc">
						<Or>
							<!-- Primo blocco AND_4 -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>S</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>LS</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.8</Literal>
								</PropertyIsGreaterThanOrEqualTo>
							</And>
							<!-- Secondo blocco AND_4 -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SL</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>L</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.8</Literal>
								</PropertyIsGreaterThanOrEqualTo>
							</And>
							<!-- Terzo blocco AND_4 -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SCL</Literal>
									</ogc:PropertyIsEqualTo>
									<And>
										<ogc:PropertyIsEqualTo>
											<ogc:PropertyName>texture</ogc:PropertyName>
											<Literal>CL</Literal>
										</ogc:PropertyIsEqualTo>
										<PropertyIsGreaterThanOrEqualTo>
											<PropertyName>clay</PropertyName>
											<Literal>27</Literal>
										</PropertyIsGreaterThanOrEqualTo>
										<PropertyIsLessThan>
											<PropertyName>clay</PropertyName>
											<Literal>35</Literal>
										</PropertyIsLessThan>
									</And>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.75</Literal>
								</PropertyIsGreaterThanOrEqualTo>
							</And>
							<!-- Quarto blocco AND_4 -->
							<And>  
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>texture</ogc:PropertyName>
									<Literal>Si</Literal>
								</ogc:PropertyIsEqualTo>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.75</Literal>
								</PropertyIsGreaterThanOrEqualTo>
							</And>
							<!-- Quinto blocco AND_4 -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SiL</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SiCL</Literal>
									</ogc:PropertyIsEqualTo>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.65</Literal>
								</PropertyIsGreaterThanOrEqualTo>
							</And>
							<!-- Sesto blocco AND_4 -->
							<And>  
								<Or>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SC</Literal>
									</ogc:PropertyIsEqualTo>
									<ogc:PropertyIsEqualTo>
										<ogc:PropertyName>texture</ogc:PropertyName>
										<Literal>SiC</Literal>
									</ogc:PropertyIsEqualTo>
									<And>
										<ogc:PropertyIsEqualTo>
											<ogc:PropertyName>texture</ogc:PropertyName>
											<Literal>CL</Literal>
										</ogc:PropertyIsEqualTo>
										<PropertyIsGreaterThanOrEqualTo>
											<PropertyName>clay</PropertyName>
											<Literal>35</Literal>
										</PropertyIsGreaterThanOrEqualTo>
									</And>
									<And>
										<ogc:PropertyIsEqualTo>
											<ogc:PropertyName>texture</ogc:PropertyName>
											<Literal>C</Literal>
										</ogc:PropertyIsEqualTo>
										<PropertyIsGreaterThanOrEqualTo>
											<PropertyName>clay</PropertyName>
											<Literal>45</Literal>
										</PropertyIsGreaterThanOrEqualTo>
									</And>
								</Or>
								<PropertyIsGreaterThanOrEqualTo>
									<PropertyName>value</PropertyName>
									<Literal>1.3</Literal>
								</PropertyIsGreaterThanOrEqualTo>
							</And>
						</Or>
					</Filter>
					<PointSymbolizer>
						<Graphic>
							<Mark>
								<WellKnownName>circle</WellKnownName>
								<Fill>
								<CssParameter name="fill">#919399</CssParameter>
								<CssParameter name="fill-opacity">1</CssParameter>
								</Fill>
								<Stroke>
								<CssParameter name="stroke">#777777</CssParameter>
								<CssParameter name="stroke-width">2</CssParameter>
								<CssParameter name="stroke-opacity">1</CssParameter>
								</Stroke>
							</Mark>
							<Size>14</Size>
						</Graphic>
					</PointSymbolizer>
				</Rule>	      
      		</FeatureTypeStyle>
    	</UserStyle>
  	</NamedLayer>
</StyledLayerDescriptor>