# Generated by Django 4.2.18 on 2025-04-17 12:17

import backoffice.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClimateAndWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "climate_weather",
                "permissions": (
                    ("access_backoffice", "Can access backoffice data"),
                    ("view_backoffice", "Can view backoffice data"),
                    ("write_backoffice", "Can write backoffice data"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cultivated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_species1",
                    models.TextField(
                        blank=True, db_comment="actual dominant specie", null=True
                    ),
                ),
                (
                    "actual_species2",
                    models.TextField(
                        blank=True, db_comment="actual second specie", null=True
                    ),
                ),
                (
                    "actual_species3",
                    models.TextField(
                        blank=True, db_comment="actual third specie", null=True
                    ),
                ),
                (
                    "cultivation_cessation",
                    models.DateField(
                        blank=True,
                        db_comment="editable if last dominant specie is NOT NULL",
                        null=True,
                    ),
                ),
                (
                    "cultivation_cover_by_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "last_species1",
                    models.TextField(
                        blank=True,
                        db_comment="last dominant specie, editable if actual_species1 is NULL",
                        null=True,
                    ),
                ),
                (
                    "last_species2",
                    models.TextField(
                        blank=True,
                        db_comment="Second last specie, editable if actual_species2 is NULL ",
                        null=True,
                    ),
                ),
                (
                    "last_species3",
                    models.TextField(
                        blank=True,
                        db_comment="Third last specie, editable if actual_species3 is NULL ",
                        null=True,
                    ),
                ),
                (
                    "rotational_species1",
                    models.TextField(
                        blank=True,
                        db_comment="Report the dominant specie that have been cultivated in the last five years in rotation with the actual or last species (the first is the most frequent)",
                        null=True,
                    ),
                ),
                (
                    "rotational_species2",
                    models.TextField(
                        blank=True,
                        db_comment="Report the second specie that have been cultivated in the last five years in rotation with the actual or last species (the first is the mostfrequent)",
                        null=True,
                    ),
                ),
                (
                    "rotational_species3",
                    models.TextField(
                        blank=True,
                        db_comment="Report the third specie that have been cultivated in the last five years in rotation with the actual or last species (the first is the mostfrequent)",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "cultivated",
                "db_table_comment": 'Report up to three actual cultivated species (in the array "actual_species") using the scientific name. If currently under fallow, report the up to 3 last species (in the array "last_species") and indicate month and year of harvest or of cultivation cessation. Insert the species in the sequence of the area covered starting with the species that covers the largest area. Report the up to 3 species that have been cultivated in the last five years in rotation with the actual or last species (1 is the most frequent) in the array column "rotational_species"',
                "permissions": (
                    ("access_backoffice", "Can access backoffice data"),
                    ("view_backoffice", "Can view backoffice data"),
                    ("write_backoffice", "Can write backoffice data"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Genealogy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_code", models.TextField(blank=True, null=True)),
                (
                    "project_id",
                    models.IntegerField(
                        blank=True,
                        db_comment="project identifier in the SIS",
                        null=True,
                    ),
                ),
                (
                    "owner_note",
                    models.TextField(
                        blank=True, db_comment="note about owner ", null=True
                    ),
                ),
                (
                    "reference",
                    models.TextField(blank=True, db_comment="reference", null=True),
                ),
                (
                    "pub_year",
                    models.IntegerField(
                        blank=True, db_comment="year of pubblication", null=True
                    ),
                ),
                ("web_link", models.TextField(blank=True, null=True)),
                (
                    "availability",
                    models.TextField(
                        blank=True,
                        db_comment="Data availability and/or use restrictions",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "profile_genealogy",
                "db_table_comment": "genealogy of profile data",
                "permissions": (
                    ("access_backoffice", "Can access backoffice data"),
                    ("view_backoffice", "Can view backoffice data"),
                    ("write_backoffice", "Can write backoffice data"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LandformTopography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gradient_upslope",
                    models.DecimalField(
                        blank=True,
                        db_comment="Ground surface upslope inclination with respect to the horizontal plane. If the profile lies on a flat surface, the gradient is 0%. ",
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "gradient_downslope",
                    models.DecimalField(
                        blank=True,
                        db_comment="Ground surface downslope inclination with respect to the horizontal plane. If the profile lies on a flat surface, the gradient is 0%. ",
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "slope_aspect",
                    models.DecimalField(
                        blank=True,
                        db_comment="If the profile lies on a slope, report the compass direction that the slope faces, viewed downslope; e.g., 225°",
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_positive],
                    ),
                ),
                (
                    "geomorphic_features_description",
                    models.TextField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "landform_topography",
                "permissions": (
                    ("access_backoffice", "Can access backoffice data"),
                    ("view_backoffice", "Can view backoffice data"),
                    ("write_backoffice", "Can write backoffice data"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LandUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "land_use",
                "permissions": (
                    ("access_backoffice", "Can access backoffice data"),
                    ("view_backoffice", "Can view backoffice data"),
                    ("write_backoffice", "Can write backoffice data"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProfileGeneral",
            fields=[
                (
                    "code",
                    models.TextField(
                        db_comment="profile identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_comment="date of the description")),
                (
                    "surveyors",
                    models.TextField(
                        blank=True,
                        db_comment="surveyors names comma separated",
                        null=True,
                    ),
                ),
                (
                    "location_name",
                    models.TextField(
                        blank=True, db_comment="Name of the profile location", null=True
                    ),
                ),
                (
                    "lat_wgs84",
                    models.DecimalField(
                        db_comment="WGS84 Latitude in decimal degree",
                        decimal_places=10,
                        max_digits=20,
                    ),
                ),
                (
                    "lon_wgs84",
                    models.DecimalField(
                        db_comment="WGS84 Longitude in decimal degree",
                        decimal_places=10,
                        max_digits=20,
                    ),
                ),
                (
                    "gps",
                    models.BooleanField(
                        blank=True, db_comment="is a gps acquisition?", null=True
                    ),
                ),
                (
                    "elevation_m_asl",
                    models.DecimalField(
                        blank=True,
                        db_comment="Altitude above the sea level in meter",
                        decimal_places=20,
                        max_digits=40,
                        null=True,
                    ),
                ),
                (
                    "elevation_dem",
                    models.DecimalField(
                        blank=True,
                        db_comment="Altitude in meters retrived from a dem in meter",
                        decimal_places=20,
                        max_digits=40,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "horizon_sequence",
                    models.TextField(
                        blank=True,
                        db_comment="Horizons sequence of the profile",
                        null=True,
                    ),
                ),
                (
                    "old_classification",
                    models.TextField(
                        blank=True,
                        db_comment="Old classification of the profile location",
                        null=True,
                    ),
                ),
                (
                    "new_classification",
                    models.TextField(
                        blank=True,
                        db_comment="New classification of the profile location",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "profile_general",
                "db_table_comment": "The Soil Profile main table",
                "permissions": (
                    ("access_backoffice", "Can access backoffice data"),
                    ("view_backoffice", "Can view backoffice data"),
                    ("write_backoffice", "Can write backoffice data"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        blank=True, db_comment="Project identifier ", null=True
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, db_comment="project name", null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="project description", null=True
                    ),
                ),
            ],
            options={
                "db_table": "project",
                "db_table_comment": "projects descriptor",
                "permissions": (
                    ("access_backoffice", "Can access backoffice data"),
                    ("view_backoffice", "Can view backoffice data"),
                    ("write_backoffice", "Can write backoffice data"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_comment="category code")),
                ("criterion", models.TextField(db_comment="category description")),
                ("taxonomy", models.TextField(db_comment="taxonomy name")),
                (
                    "super",
                    models.TextField(
                        blank=True, db_comment="super category name", null=True
                    ),
                ),
            ],
            options={
                "db_table": "taxonomy",
                "db_table_comment": "SOILS4MED Taxonomies from WRB2022 Taxonomies",
                "permissions": (
                    ("access_backoffice", "Can access backoffice data"),
                    ("view_backoffice", "Can view backoffice data"),
                    ("write_backoffice", "Can write backoffice data"),
                ),
                "managed": True,
                "unique_together": {("taxonomy", "name")},
            },
        ),
        migrations.CreateModel(
            name="Surface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surface_crusts_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                ("bedrock_formation_name", models.TextField(blank=True, null=True)),
                (
                    "outcrops_area_covered",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "outcrops_average_distance",
                    models.DecimalField(
                        blank=True, decimal_places=20, max_digits=40, null=True
                    ),
                ),
                (
                    "outcrops_size",
                    models.DecimalField(
                        blank=True, decimal_places=20, max_digits=40, null=True
                    ),
                ),
                (
                    "ground_water_depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[backoffice.models.validate_positive],
                    ),
                ),
                (
                    "desert_ventifacts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "desert_varnish",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "bedrock_lithology",
                    models.ForeignKey(
                        blank=True,
                        db_column="bedrock_lithology",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "patterned_ground_form",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Patterned ground form field",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_patterned_ground_form_set",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "technical_surface_alteration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_technical_surface_alteration_set",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "water_above_surface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_water_above_surface_set",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "water_drainage_condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_water_drainage_condition_set",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "water_repellence_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_water_repellence_type_set",
                        to="backoffice.taxonomy",
                    ),
                ),
            ],
            options={
                "db_table": "surface",
                "permissions": (
                    ("access_backoffice", "Can access backoffice data"),
                    ("view_backoffice", "Can view backoffice data"),
                    ("write_backoffice", "Can write backoffice data"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProfileLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.TextField(db_comment="Horizon designation")),
                (
                    "layer_number",
                    models.SmallIntegerField(
                        db_comment="layer order in profile",
                        validators=[backoffice.models.validate_positive],
                    ),
                ),
                (
                    "upper",
                    models.DecimalField(
                        db_comment="upper depth in cm",
                        decimal_places=2,
                        max_digits=12,
                        validators=[backoffice.models.validate_positive],
                    ),
                ),
                (
                    "lower",
                    models.DecimalField(
                        db_comment="lower depth in cm",
                        decimal_places=2,
                        max_digits=12,
                        validators=[backoffice.models.validate_positive],
                    ),
                ),
                (
                    "homogeneity_part",
                    models.DecimalField(
                        blank=True,
                        db_comment="Described parts, by exposed area [%]",
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "initial_weathering",
                    models.DecimalField(
                        db_comment="Initial weathering abundance",
                        decimal_places=2,
                        max_digits=6,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "soluble_salts",
                    models.DecimalField(
                        blank=True,
                        db_comment="ECSE [dS m-1m-1]",
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "field_ph_misured_value",
                    models.DecimalField(
                        blank=True,
                        db_comment="Potentiometric pH measurement - Measured value",
                        decimal_places=20,
                        max_digits=40,
                        null=True,
                    ),
                ),
                (
                    "continuity_volume_fractures",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "continuity_average_fractures",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[backoffice.models.validate_percentage],
                    ),
                ),
                (
                    "bulk_density",
                    models.DecimalField(
                        blank=True, decimal_places=20, max_digits=40, null=True
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "boundaries_distinctness",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Distinctness of the layer's lower boundary",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boundaries_distinctness_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "boundaries_shape",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boundaries_shape_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "field_ph_solution",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Potentiometric pH measurement - Solution and mixing ratio",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_ph_solution_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "homogeneity_alluvial_tephra",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Layer composed of several strata of alluvial sediments or of tephra",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homogeneity_alluvial_tephra_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "organicmineral",
                    models.ForeignKey(
                        blank=True,
                        db_comment="organic, organotechnic or mineral layer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organicmineral_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "packing_density",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Estimate the packing density using a knife with a blade approx. 10 cm long",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packing_density_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "parent_material",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Report the parent material. Use the help of a geological map.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_material_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        db_comment="Foreign Key field: profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layer_profile_set",
                        to="backoffice.profilegeneral",
                    ),
                ),
                (
                    "rh_value",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Rh Value",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rh_value_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "texture_class",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Texture class",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="texture_class_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "texture_subclass",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Texture subclass",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="texture_subclass_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "volcanic_glasses_abundance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="volcanic_glasses_abundance_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "volcanic_glasses_thixotropy_naf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="volcanic_glasses_thixotropy_naf_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "water_saturation",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Types of water saturation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="water_saturation_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "water_status",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Soil water status",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="water_status_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
                (
                    "wind_disposition",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Wind deposition",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wind_disposition_layers",
                        to="backoffice.taxonomy",
                    ),
                ),
            ],
            options={
                "db_table": "layer",
                "permissions": (
                    ("access_backoffice", "Can access backoffice data"),
                    ("view_backoffice", "Can view backoffice data"),
                    ("write_backoffice", "Can write backoffice data"),
                ),
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="profilegeneral",
            name="classification_sys",
            field=models.ForeignKey(
                blank=True,
                db_comment="value from p_classification_system ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profilehorizonsequence_classification_sys_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="profilegeneral",
            name="climate_weather",
            field=models.OneToOneField(
                db_comment="Climate weather Section",
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="backoffice.climateandweather",
            ),
        ),
        migrations.AddField(
            model_name="profilegeneral",
            name="genealogy",
            field=models.OneToOneField(
                db_comment="Profile Genealogy",
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="backoffice.genealogy",
            ),
        ),
        migrations.AddField(
            model_name="profilegeneral",
            name="landform_topography",
            field=models.OneToOneField(
                db_comment="landform_topography Section",
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="backoffice.landformtopography",
            ),
        ),
        migrations.AddField(
            model_name="profilegeneral",
            name="landuse",
            field=models.OneToOneField(
                db_comment="LandUse Section",
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="backoffice.landuse",
            ),
        ),
        migrations.AddField(
            model_name="profilegeneral",
            name="project",
            field=models.ForeignKey(
                blank=True,
                db_comment="Survey/Project identifier",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_project_set",
                to="backoffice.project",
            ),
        ),
        migrations.AddField(
            model_name="profilegeneral",
            name="surface",
            field=models.OneToOneField(
                db_comment="Surface Section",
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="backoffice.surface",
            ),
        ),
        migrations.AddField(
            model_name="profilegeneral",
            name="survey_method",
            field=models.ForeignKey(
                blank=True,
                db_comment="The code of the survey method",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_survey_method_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="landuse",
            name="corine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corine_landuses",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="landuse",
            name="cultivated",
            field=models.OneToOneField(
                db_comment="Cultivated Section",
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="backoffice.cultivated",
            ),
        ),
        migrations.AddField(
            model_name="landuse",
            name="land_use",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="land_use_landuses",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="landformtopography",
            name="landform1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="landform1_landforms",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="landformtopography",
            name="landform1_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="landform1_activity_landforms",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="landformtopography",
            name="landform2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="landform2_landforms",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="landformtopography",
            name="landform2_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="landform2_activity_landforms",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="landformtopography",
            name="profile_position",
            field=models.ForeignKey(
                blank=True,
                db_comment="If the profile lies in an uneven terrain, report the profile position.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_position_landforms",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="landformtopography",
            name="slope_shape",
            field=models.ForeignKey(
                blank=True,
                db_comment="If the profile lies on a slope, report the slope shape in 2 directions: up-/downslope (perpendicular to the elevation contour, i.e. the vertical curvature) and across slope (along the elevation contour, i.e. the horizontal curvature); e.g., Linear (L), Convex (V) or Concave (C).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slope_shape_landforms",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="cultivated",
            name="cultivation_type",
            field=models.ForeignKey(
                blank=True,
                db_column="cultivation_type",
                db_comment="value from p_cultivation_type ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="cultivated",
            name="spec_prod_tech1",
            field=models.ForeignKey(
                blank=True,
                db_column="spec_prod_tech1",
                db_comment="Report the techniques that refer to the surrounding area of the soil profile. If more than one type of technique is present, report in the array up to three, the dominant one first. Value from p_productivity_techniques",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profilecultivated_special_productivity_technique1_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="cultivated",
            name="spec_prod_tech2",
            field=models.ForeignKey(
                blank=True,
                db_column="spec_prod_tech2",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profilecultivated_special_productivity_technique2_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="cultivated",
            name="spec_prod_tech3",
            field=models.ForeignKey(
                blank=True,
                db_column="spec_prod_tech3",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profilecultivated_special_productivity_technique3_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="climateandweather",
            name="climate_koppen",
            field=models.ForeignKey(
                blank=True,
                db_column="climate_koppen",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profileclimateweather_climate_koppen_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="climateandweather",
            name="current_weather",
            field=models.ForeignKey(
                blank=True,
                db_column="current_weather",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profileclimateweather_current_weather_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="climateandweather",
            name="ecozone_shultz",
            field=models.ForeignKey(
                blank=True,
                db_column="ecozone_shultz",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profileclimateweather_ecozone_shultz_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="climateandweather",
            name="past_weather",
            field=models.ForeignKey(
                blank=True,
                db_column="past_weather",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profileclimateweather_past_weather_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="climateandweather",
            name="season",
            field=models.ForeignKey(
                blank=True,
                db_column="season",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profileclimateweather_season_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="climateandweather",
            name="soil_moist_regime",
            field=models.ForeignKey(
                blank=True,
                db_column="soil_moist_regime",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profileclimateweather_soil_moist_regime_set",
                to="backoffice.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="climateandweather",
            name="soil_temp_regime",
            field=models.ForeignKey(
                blank=True,
                db_column="soil_temp_regime",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profileclimateweather_soil_temp_regime_set",
                to="backoffice.taxonomy",
            ),
        ),
    ]
