# Generated by Django 5.2.8 on 2026-06-24 14:30
# WARNING 1, Django ERROR: psycopg stop migrations for %, change : % to  %%   
# WARNING 2, the use of %% instead % generates the Django message: 
# ---Your models in app(s): 'backoffice' have changes that are not yet reflected in a migration, and so won't be applied.
# ---Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
# So be carefull when made new migrations 

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="context",
            field=models.TextField(
                choices=[
                    ("POINTS_SOIL_DATA", "POINTS_SOIL_DATA"),
                    ("SOIL_INDICATOR", "SOIL_INDICATOR"),
                    ("AOI_SOIL_INDICATOR", "AOI_SOIL_INDICATOR"),
                ],
                db_comment="Dataset Context: Points or Indicators",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="status",
            field=models.TextField(
                choices=[
                    ("CREATED", "CREATED"),
                    ("CONFIGURED", "CONFIGURED"),
                    ("VALIDATED", "VALIDATED"),
                    ("IN_PROCESS", "IN_PROCESS"),
                    ("PUBLISHED", "PUBLISHED"),
                    ("ERRORS", "ERRORS"),
                ],
                db_comment="Status of the dataset",
            ),
        )
    ]
