# Generated by Django 4.2.9 on 2025-06-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilegeneral",
            name="climateandweather",
            field=models.OneToOneField(
                blank=True,
                db_comment="Climate weather",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.climateandweather",
            ),
        ),
        migrations.AlterField(
            model_name="profilegeneral",
            name="coarsefragments",
            field=models.OneToOneField(
                blank=True,
                db_comment="Coarse Fragments",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.coarsefragments",
            ),
        ),
        migrations.AlterField(
            model_name="profilegeneral",
            name="genealogy",
            field=models.OneToOneField(
                blank=True,
                db_comment="Profile Genealogy",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.genealogy",
            ),
        ),
        migrations.AlterField(
            model_name="profilegeneral",
            name="landformtopography",
            field=models.OneToOneField(
                blank=True,
                db_comment="landform_topography",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.landformtopography",
            ),
        ),
        migrations.AlterField(
            model_name="profilegeneral",
            name="landuse",
            field=models.OneToOneField(
                blank=True,
                db_comment="Land Use ",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.landuse",
            ),
        ),
        migrations.AlterField(
            model_name="profilegeneral",
            name="litterlayer",
            field=models.OneToOneField(
                blank=True,
                db_comment="Litter Layer",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.litterlayer",
            ),
        ),
        migrations.AlterField(
            model_name="profilegeneral",
            name="surface",
            field=models.OneToOneField(
                blank=True,
                db_comment="Surface ",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.surface",
            ),
        ),
        migrations.AlterField(
            model_name="profilegeneral",
            name="surfacecracks",
            field=models.OneToOneField(
                blank=True,
                db_comment="Surface cracks",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.surfacecracks",
            ),
        ),
        migrations.AlterField(
            model_name="profilegeneral",
            name="surfaceunevenness",
            field=models.OneToOneField(
                blank=True,
                db_comment="Surface Unevenness",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backoffice.surfaceunevenness",
            ),
        ),
    ]
