# Generated by Django 4.2.17 on 2025-05-15 12:07

from django.db import migrations

SQL_CREATE = f"""
    CREATE OR REPLACE VIEW profile_general_geo AS
    SELECT
      t.code,t.date,t.surveyors,t.location,t.lat_wgs84,t.lon_wgs84,t.gps,t.elev_m_asl,
      t.elev_dem,t.survey_m,notes,horizons,old_cls,new_cls,cls_sys,project,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t;

    CREATE OR REPLACE VIEW surface_unevenness_geo AS
    SELECT
      t.code,
      s.*,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t, surface_unevenness s
    WHERE t.surfaceunevenness = s.id;

    CREATE OR REPLACE VIEW surface1_geo AS
    SELECT
      t.code,
      s1.*,
      s2.*,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t, litter_layer s1, surface_cracks s2
    WHERE t.litterlayer = s1.id AND t.surfacecracks = s2.id;

    CREATE OR REPLACE VIEW surface2_geo AS
    SELECT
      t.code,
      s.*,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t, surface s
    WHERE t.surface = s.id;

    CREATE OR REPLACE VIEW landuse1_geo AS
    SELECT
      t.code,
      l1.corine,
      l1.land_use,
      l2.*,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t, land_use l1, cultivated l2
    WHERE t.landuse = l1.id AND l1.cultivated = l2.id;

    CREATE OR REPLACE VIEW landuse2_geo AS
    SELECT
      t.code,
      l1.corine,
      l1.land_use,
      l2.*,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t, land_use l1, not_cultivated l2
    WHERE t.landuse = l1.id AND l2.landuse = l1.id;
    
    CREATE OR REPLACE VIEW climate_weather_geo AS
    SELECT
      t.code,
      c.*,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t, climate_weather c
    WHERE t.climate_weather = c.id;

    CREATE OR REPLACE VIEW coarse_fragments_geo AS
    SELECT
      t.code,
      c.*,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t, coarsefragments c
    WHERE t.coarsefragments = c.id;

    CREATE OR REPLACE VIEW landform_topography_geo AS
    SELECT
      t.code,
      c.*,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t, landform_topography c
    WHERE t.landformtopography = c.id;

    CREATE OR REPLACE VIEW profilelayer_geo AS
    SELECT
      t.code,
      l.profile,l.design,l.number,l.upper,l.lower,l.lower_bound,l.hom_part,
      l.hom_alluvt,l.wat_satur,l.wat_status,l.o_mineral,l.bounddist,l.boundshape,
      l.wind,l.tex_cls,l.tex_subcls,l.struct_w_s,l.rh_value,l.weathering,l.sol_salts,
      l.ph_value,l.ph_solution,l.fracts,l.avg_fracts,l.volc_abund,l.volc_thnaf,
      l.bulk_dens,l.pack_dens,l.parent_mat,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t, profile_layer l
    WHERE t.code = l.profile;

    CREATE OR REPLACE VIEW labdata_geo AS
    SELECT
      t.code,
      pl.design,
      pl.number,
      pl.upper,
      pl.lower,
      pl.lower_bound,
      l.*,
      ST_SetSRID(
        ST_MakePoint(t.lon_wgs84, t.lat_wgs84),
        4326
      ) AS geom
    FROM profile_general t, profile_layer pl, lab_data l
    WHERE t.code = pl.profile AND pl.labdata = l.id;

"""
## todo
# coarsefragments,artefacts,cracks,stressfeatures,coatingsbridges,ribbonlikeaccumulations,
# carbonates,gypsum ,secondarysilica, consistence, surfacecrusts,permafrost,
# remnants,organiccarbon,roots,animalactivity,humanalterations,degreedecomposition,
# nonmatrixpore,labdata,matrixcolours,texturecolour,lithogenicvariegates,redoximorphicfeatures
####
## todo2 SAMPLES
SQL_DROP = f"""
  DROP VIEW IF EXISTS  profile_general_geo CASCADE;"
  DROP VIEW IF EXISTS  surface_unevenness_geo CASCADE;"
  DROP VIEW IF EXISTS  surface1_geo CASCADE;"
  DROP VIEW IF EXISTS  surface2_geo CASCADE;"
  DROP VIEW IF EXISTS  landuse1_geo CASCADE;"
  DROP VIEW IF EXISTS  landuse2_geo CASCADE;"
  DROP VIEW IF EXISTS  climate_weather_geo CASCADE;"
  DROP VIEW IF EXISTS  coarse_fragments_geo CASCADE;"
  DROP VIEW IF EXISTS  landform_topography_geo CASCADE;"
  DROP VIEW IF EXISTS  labdata_geo CASCADE;"
  DROP VIEW IF EXISTS  profilelayer_geo CASCADE;"

"""  
class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL_CREATE,
            reverse_sql=SQL_DROP,
        ),

    ]
