# Generated by Django 4.2.9 on 2025-06-11 06:47

import backoffice.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0002_alter_profilegeneral_climateandweather_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilelayer",
            name="design",
            field=models.TextField(
                blank=True, db_comment="layer horizon designation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="profilelayer",
            name="lower_bound",
            field=models.TextField(
                blank=True, db_comment="layer lower boundary ", null=True
            ),
        ),
        migrations.AlterField(
            model_name="profilelayer",
            name="number",
            field=models.SmallIntegerField(
                blank=True,
                db_comment="layer order in profile",
                null=True,
                validators=[backoffice.models.validate_positive],
            ),
        ),
        migrations.AlterField(
            model_name="profilelayer",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign Key field: profile",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profilelayer_profile_set",
                to="backoffice.profilegeneral",
            ),
        ),
    ]
