# Generated by Django 4.2.9 on 2025-06-11 06:54

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0003_alter_profilelayer_design_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilelayer",
            name="weathering",
            field=models.DecimalField(
                blank=True,
                db_comment="Initial weathering abundance",
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
    ]
