# Generated by Django 4.2.24 on 2025-10-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0003_alter_pointgeneral_project_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="gn_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="gn_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="gn_thumb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="xlsxupload",
            name="type",
            field=models.TextField(
                choices=[
                    ("XLS_P", "XLSx Points Soil Data Upload"),
                    ("XLS_PH", "XLSx Photo Data upload"),
                    ("XLS_PJ", "XLSx Projects Data upload"),
                ],
                db_comment="Type of the upload",
            ),
        ),
    ]
