# Generated by Django 5.2.8 on 2026-07-02 19:42

import backoffice.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0004_sqlview_indicators"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="labdataextrameasure",
            table_comment="Laboratory data of extra measures types not present in labadata",
        ),
        migrations.AlterUniqueTogether(
            name="labdataextrameasure",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="labdataextrameasure",
            name="date",
            field=models.DateTimeField(
                blank=True, db_comment="Date of the sample", null=True
            ),
        ),
        migrations.AddField(
            model_name="labdataextrameasure",
            name="lower",
            field=models.FloatField(
                blank=True,
                db_comment="Sampling lower boundary",
                null=True,
                validators=[backoffice.models.validate_positive],
            ),
        ),
        migrations.AddField(
            model_name="labdataextrameasure",
            name="upper",
            field=models.FloatField(
                blank=True,
                db_comment="Sampling upper boundary",
                null=True,
                validators=[backoffice.models.validate_positive],
            ),
        ),
        migrations.AlterField(
            model_name="xlsxupload",
            name="data",
            field=models.JSONField(db_comment="Upload Json Data"),
        ),
        migrations.CreateModel(
            name="BaseDataset",
            fields=[
                (
                    "code",
                    models.TextField(
                        db_comment="Geoserver typename and Database SQL view name of the point soil data section",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True, db_comment="Title of the dataset", null=True
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True, db_comment="Abstract of the dataset", null=True
                    ),
                ),
                (
                    "geonode_id",
                    models.TextField(
                        blank=True, db_comment="catalogue identifier", null=True
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("TO_CONFIGURE", "TO_CONFIGURE"),
                            ("CREATED", "CREATED"),
                            ("IN_PROCESS", "IN_PROCESS"),
                            ("PUBLISHED", "PUBLISHED"),
                            ("ERRORS", "ERRORS"),
                        ],
                        db_comment="Status of the dataset",
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("SOIL_INDICATOR", "SOIL_INDICATOR"),
                            ("POINT_SOIL_DATA_SECTION", "POINT_SOIL_DATA_SECTION"),
                        ],
                        db_comment="Type of the dataset",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, db_comment="keywords comma separated", null=True
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sis_measure_unit_set",
                        to="backoffice.taxonomyvalue",
                    ),
                ),
            ],
            options={
                "db_table": "base_dataset_section",
                "db_table_comment": "Base Dataset of Soil Data",
                "managed": True,
            },
        ),
    ]
