# Generated by Django 4.2.9 on 2025-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0004_alter_profilelayer_weathering"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="layerstructure",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="layerstructure",
            constraint=models.UniqueConstraint(
                condition=models.Q(("level__isnull", False)),
                fields=("layer", "level"),
                name="unique_layer_level_not_null",
            ),
        ),
    ]
