# Generated by Django 5.2.8 on 2026-07-12 16:06

import backoffice.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0005_alter_labdataextrameasure_table_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basedataset",
            name="keywords",
        ),
        migrations.AlterField(
            model_name="basedataset",
            name="type",
            field=models.TextField(
                choices=[
                    ("soil_chemical_health", "soil_chemical_health"),
                    ("soil_physical_health", "soil_physical_health"),
                    ("soil_biological_health", "soil_biological_health"),
                    ("points_soil_data", "points_soil_data"),
                ],
                db_comment="Type of the dataset",
            ),
        ),
        migrations.AlterField(
            model_name="taxonomyvalue",
            name="uri",
            field=models.TextField(
                blank=True, db_comment="uri to a controlled vocubolary entry", null=True
            ),
        ),
        migrations.AlterField(
            model_name="xlsxupload",
            name="data",
            field=models.JSONField(db_comment="Upload Json Data"),
        ),
        migrations.CreateModel(
            name="HydroPtfElaboration",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(db_comment="Elaboration title")),
                ("date", models.DateTimeField(db_comment="Date of the elaboration")),
                ("input_data", models.JSONField(db_comment="Input Data")),
                ("useBulkDensity", 
                    models.BooleanField( 
                        db_comment="It indicates the presence of the bulk density in the input data",
                        default=False,
                    ), 
                ),
                (
                    "output_data", 
                    models.JSONField(
                        blank=True, db_comment="Input Data", null=True 
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("CREATED", "CREATED"),
                            ("IN_PROCESS", "IN_PROCESS"),
                            ("SUCCESS", "SUCCESS"),
                            ("ERRORS", "ERRORS"),
                        ],
                        db_comment="Status of the Hydro PTF Elaboration",
                    ),
                ),
            ],
            options={
                "db_table": "hydroptf_elaboration",
                "db_table_comment": "hydroptf elaborations",
                "managed": True,
            },
        ),
    ]
