# Generated by Django 5.2.8 on 2026-04-13 12:29

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0005_alter_layercoatingsbridges_table_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="layercoatingsbridges",
            table_comment="Report the abundance of clay coatings in % of the surfaces of soil aggregates, coarse fragments and/or biopore walls clay bridges between sand grains in % of involved sand grains.",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="geonode_id",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="k_measure",
        ),
        migrations.AddField(
            model_name="dataset",
            name="catalogue_id",
            field=models.TextField(
                blank=True, db_comment="Geonode Id of the dataset", null=True
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="typename",
            field=models.TextField(
                blank=True, db_comment="Geoserver typename of the result", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="filter",
            field=models.JSONField(
                blank=True, db_comment="Filter parameters", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="points",
            field=models.JSONField(
                blank=True, db_comment="Source soil points data", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="status",
            field=models.TextField(
                choices=[
                    ("CREATED", "CREATED"),
                    ("CONFIGURED", "CONFIGURED"),
                    ("IN_PREPROCESS", "IN PREPROCESS"),
                    ("PREPROCESSED", "PREPROCESSED"),
                    ("VALIDATED", "VALIDATED"),
                    ("IN_PROCESS", "IN PROCESS"),
                    ("PUBLISHED", "PUBLISHED"),
                    ("ERRORS", "ERRORS"),
                ],
                db_comment="Status of the dataset",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="user",
            field=models.TextField(db_comment="SIS Staff member id"),
        ),
        migrations.AlterField(
            model_name="labdata",
            name="gravel",
            field=models.FloatField(
                blank=True,
                db_comment="Gravel content (%)",
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
        migrations.AlterField(
            model_name="landformtopography",
            name="grad_downs",
            field=models.FloatField(
                blank=True,
                db_comment="Ground surface downslope inclination with respect to the horizontal plane. If the profile lies on a flat surface, the gradient is 0%. ",
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
        migrations.AlterField(
            model_name="landformtopography",
            name="grad_ups",
            field=models.FloatField(
                blank=True,
                db_comment="Ground surface upslope inclination with respect to the horizontal plane. If the profile lies on a flat surface, the gradient is 0%. ",
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
        migrations.AlterField(
            model_name="layerredoximorphic",
            name="abund_oxi",
            field=models.FloatField(
                blank=True,
                db_comment="Abundance of cemented oximorphic features, by volume [%]",
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
        migrations.AlterField(
            model_name="pointlayer",
            name="coars_text_depth",
            field=models.FloatField(
                blank=True,
                db_comment="the depth range in cm, where these tongues cover ≥ 10% of the exposed area (if they extend across several layers, the length is only reported in the description of that layer, where they start at the layer’s upper limit).",
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
        migrations.AlterField(
            model_name="pointlayer",
            name="coars_text_v_tongues",
            field=models.FloatField(
                blank=True,
                db_comment="the percentage (by exposed area) occupied by continuous vertical tongues of coarser-textured parts with a horizontal extension of ≥ 1 cm (if these tongues are absent, report 0%)",
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
        migrations.AlterField(
            model_name="pointlayer",
            name="hom_part",
            field=models.FloatField(
                blank=True,
                db_comment="Described parts, by exposed area [%]",
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
        migrations.AlterField(
            model_name="pointlayer",
            name="stress_fts_pressfaces",
            field=models.FloatField(
                blank=True,
                db_comment="Pressure faces in % of the surfaces of soil aggregates",
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
        migrations.AlterField(
            model_name="pointlayer",
            name="stress_fts_slicksides",
            field=models.FloatField(
                blank=True,
                db_comment="Slickensides in % of the surfaces of soil aggregates.",
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
        migrations.AlterField(
            model_name="pointlayer",
            name="struct_w_s",
            field=models.FloatField(
                blank=True,
                db_comment="Structure Wedge-shaped aggregates tilted between ≥ 10° and ≤ 60° from the horizontal: abundance, by volume [%]",
                null=True,
                validators=[backoffice.models.validate_percentage],
            ),
        ),
    ]
