from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *


router = DefaultRouter()
router.register(r'xlsx-uploads', XLSxUploadViewSet)
router.register(r'projects', ProjectViewSet)
router.register(r'profile-generals', ProfileGeneralViewSet)
router.register(r'landform-topographies', LandformTopographyViewSet)
router.register(r'coarse-fragments', CoarseFragmentsViewSet)
router.register(r'climate-and-weathers', ClimateAndWeatherViewSet)
router.register(r'cultivated', CultivatedViewSet)
router.register(r'land-uses', LandUseViewSet)
router.register(r'not-cultivated', NotCultivatedViewSet)
router.register(r'surfaces', SurfaceViewSet)
router.register(r'surface-cracks', SurfaceCracksViewSet)
router.register(r'litter-layers', LitterLayerViewSet)
router.register(r'surface-unevenness', SurfaceUnevennessViewSet)
router.register(r'profile-layers', ProfileLayerViewSet)
router.register(r'layer-remnants', LayerRemnantsViewSet )
router.register(r'layer-coarse-fragments', LayerCoarseFragmentsViewSet)
router.register(r'layer-artefacts', LayerArtefactsViewSet)
router.register(r'layer-cracks', LayerCracksViewSet)
router.register(r'layer-stress-features', LayerStressFeaturesViewSet)
router.register(r'layer-matrix-colours', LayerMatrixColoursViewSet)
router.register(r'layer-coarser-textured', LayerCoarserTexturedViewSet)
router.register(r'layer-lithogenic-variegates', LayerLithogenicVariegatesViewSet)
router.register(r'layer-redoximorphic-features', LayerRedoximorphicFeaturesViewSet)
router.register(r'layer-redoximorphic-colours', LayerRedoximorphicColourViewSet)
router.register(r'layer-coatings-bridges', LayerCoatingsBridgesViewSet)
router.register(r'layer-ribbonlike-accumulations', LayerRibbonlikeAccumulationsViewSet)
router.register(r'layer-carbonates', LayerCarbonatesViewSet)
router.register(r'layer-gypsum', LayerGypsumViewSet)
router.register(r'layer-secondary-silica', LayerSecondarySilicaViewSet)
router.register(r'layer-consistences', LayerConsistenceViewSet)
router.register(r'layer-surface-crusts', LayerSurfaceCrustsViewSet)
router.register(r'layer-permafrost-features', LayerPermafrostFeaturesViewSet)
router.register(r'layer-organic-carbon', LayerOrganicCarbonViewSet)
router.register(r'layer-roots', LayerRootsViewSet)
router.register(r'layer-animal-activities', LayerAnimalActivityViewSet)
router.register(r'layer-human-alterations', LayerHumanAlterationsViewSet)
router.register(r'layer-degree-decomposition', LayerDegreeDecompositionViewSet)
router.register(r'layer-non-matrix-pores', LayerNonMatrixPoreViewSet)
router.register(r'layer-structures', LayerStructureViewSet)
router.register(r'lab-data', LabDataViewSet)
router.register(r'sample-generals', SampleGeneralViewSet)
router.register(r'sample-landform-topographies', SampleLandformTopographyViewSet)
router.register(r'sample-coarse-fragments', SampleCoarseFragmentsViewSet)
router.register(r'sample-climate-and-weathers', SampleClimateAndWeatherViewSet)
router.register(r'sample-cultivated', SampleCultivatedViewSet)
router.register(r'sample-land-uses', SampleLandUseViewSet)
router.register(r'sample-not-cultivated', SampleNotCultivatedViewSet)
router.register(r'sample-surfaces', SampleSurfaceViewSet)
router.register(r'sample-surface-cracks', SampleSurfaceCracksViewSet)
router.register(r'sample-litter-layers', SampleLitterLayerViewSet)
router.register(r'sample-surface-unevenness', SampleSurfaceUnevennessViewSet)
router.register(r'sample-surface-crusts', SampleSurfaceCrustsViewSet)
router.register(r'sample-layers', SampleLayerViewSet)
router.register(r'sample-layer-remnants', SampleLayerRemnantsViewSet )
router.register(r'sample-layer-coarse-fragments', SampleLayerCoarseFragmentsViewSet)
router.register(r'sample-layer-artefacts', SampleLayerArtefactsViewSet)
router.register(r'sample-layer-cracks', SampleLayerCracksViewSet)
router.register(r'sample-layer-stress-features', SampleLayerStressFeaturesViewSet)
router.register(r'sample-layer-matrix-colours', SampleLayerMatrixColoursViewSet)
router.register(r'sample-layer-coarser-textured', LayerCoarserTexturedViewSet)
router.register(r'sample-layer-lithogenic-variegates', SampleLayerLithogenicVariegatesViewSet)
router.register(r'sample-layer-redoximorphic-features', SampleLayerRedoximorphicFeaturesViewSet)
router.register(r'sample-layer-redoximorphic-colours', SampleLayerRedoximorphicColourViewSet)
router.register(r'sample-layer-coatings-bridges', SampleLayerCoatingsBridgesViewSet)
router.register(r'sample-layer-ribbonlike-accumulations', SampleLayerRibbonlikeAccumulationsViewSet)
router.register(r'sample-layer-carbonates', SampleLayerCarbonatesViewSet)
router.register(r'sample-layer-gypsum', SampleLayerGypsumViewSet)
router.register(r'sample-layer-secondary-silica', SampleLayerSecondarySilicaViewSet)
router.register(r'sample-layer-consistences', SampleLayerConsistenceViewSet)
router.register(r'sample-layer-permafrost-features', SampleLayerPermafrostFeaturesViewSet)
router.register(r'sample-layer-organic-carbon', SampleLayerOrganicCarbonViewSet)
router.register(r'sample-layer-roots', SampleLayerRootsViewSet)
router.register(r'sample-layer-animal-activities', SampleLayerAnimalActivityViewSet)
router.register(r'sample-layer-human-alterations', SampleLayerHumanAlterationsViewSet)
router.register(r'sample-layer-degree-decomposition', SampleLayerDegreeDecompositionViewSet)
router.register(r'sample-layer-non-matrix-pores', SampleLayerNonMatrixPoreViewSet)
router.register(r'sample-layer-structures', SampleLayerStructureViewSet)
router.register(r'sample-lab-data', SampleLabDataViewSet)
router.register(r'indicators', IndicatorViewSet)
router.register(r'requests', RequestViewSet)

 
urlpatterns = [
    path('', include(router.urls)),
]