from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *


router = DefaultRouter()
router.register(r'xlsx-uploads', XLSxUploadViewSet)
router.register(r'projects', ProjectViewSet)
router.register(r'profile-generals', ProfileGeneralViewSet)
router.register(r'landform-topographies', LandformTopographyViewSet)
router.register(r'coarse-fragments', CoarseFragmentsViewSet)
router.register(r'climate-and-weathers', ClimateAndWeatherViewSet)
router.register(r'cultivated', CultivatedViewSet)
router.register(r'land-uses', LandUseViewSet)
router.register(r'not-cultivated', NotCultivatedViewSet)
router.register(r'surfaces', SurfaceViewSet)
router.register(r'surface-cracks', SurfaceCracksViewSet)
router.register(r'litter-layers', LitterLayerViewSet)
router.register(r'surface-unevenness', SurfaceUnevennessViewSet)
router.register(r'profile-layers', ProfileLayerViewSet)
router.register(r'layer-remnants', LayerRemnantsViewSet )
router.register(r'layer-coarse-fragments', LayerCoarseFragmentsViewSet)
router.register(r'layer-artefacts', LayerArtefactsViewSet)
router.register(r'layer-cracks', LayerCracksViewSet)
router.register(r'layer-stress-features', LayerStressFeaturesViewSet)
router.register(r'layer-matrix-colours', LayerMatrixColoursViewSet)
router.register(r'layer-coarser-textured', LayerCoarserTexturedViewSet)
router.register(r'layer-lithogenic-variegates', LayerLithogenicVariegatesViewSet)
router.register(r'layer-redoximorphic-features', LayerRedoximorphicFeaturesViewSet)
router.register(r'layer-redoximorphic-colours', LayerRedoximorphicColourViewSet)
router.register(r'layer-coatings-bridges', LayerCoatingsBridgesViewSet)
router.register(r'layer-ribbonlike-accumulations', LayerRibbonlikeAccumulationsViewSet)
router.register(r'layer-carbonates', LayerCarbonatesViewSet)
router.register(r'layer-gypsum', LayerGypsumViewSet)
router.register(r'layer-secondary-silica', LayerSecondarySilicaViewSet)
router.register(r'layer-consistences', LayerConsistenceViewSet)
router.register(r'layer-surface-crusts', LayerSurfaceCrustsViewSet)
router.register(r'layer-permafrost-features', LayerPermafrostFeaturesViewSet)
router.register(r'layer-organic-carbon', LayerOrganicCarbonViewSet)
router.register(r'layer-roots', LayerRootsViewSet)
router.register(r'layer-animal-activities', LayerAnimalActivityViewSet)
router.register(r'layer-human-alterations', LayerHumanAlterationsViewSet)
router.register(r'layer-degree-decomposition', LayerDegreeDecompositionViewSet)
router.register(r'layer-non-matrix-pores', LayerNonMatrixPoreViewSet)
router.register(r'layer-structures', LayerStructureViewSet)
router.register(r'lab-data', LabDataViewSet)
router.register(r'monitoring-generals', MonitoringGeneralViewSet)
router.register(r'monitoring-landform-topographies', MonitoringLandformTopographyViewSet)
router.register(r'monitoring-coarse-fragments', MonitoringCoarseFragmentsViewSet)
router.register(r'monitoring-climate-and-weathers', MonitoringClimateAndWeatherViewSet)
router.register(r'monitoring-cultivated', MonitoringCultivatedViewSet)
router.register(r'monitoring-land-uses', MonitoringLandUseViewSet)
router.register(r'monitoring-not-cultivated', MonitoringNotCultivatedViewSet)
router.register(r'monitoring-surfaces', MonitoringSurfaceViewSet)
router.register(r'monitoring-surface-cracks', MonitoringSurfaceCracksViewSet)
router.register(r'monitoring-litter-layers', MonitoringLitterLayerViewSet)
router.register(r'monitoring-surface-unevenness', MonitoringSurfaceUnevennessViewSet)
router.register(r'monitoring-surface-crusts', MonitoringSurfaceCrustsViewSet)
router.register(r'monitoring-layers', MonitoringLayerViewSet)
router.register(r'monitoring-layer-remnants', MonitoringLayerRemnantsViewSet )
router.register(r'monitoring-layer-coarse-fragments', MonitoringLayerCoarseFragmentsViewSet)
router.register(r'monitoring-layer-artefacts', MonitoringLayerArtefactsViewSet)
router.register(r'monitoring-layer-cracks', MonitoringLayerCracksViewSet)
router.register(r'monitoring-layer-stress-features', MonitoringLayerStressFeaturesViewSet)
router.register(r'monitoring-layer-matrix-colours', MonitoringLayerMatrixColoursViewSet)
router.register(r'monitoring-layer-coarser-textured',  MonitoringLayerCoarserTexturedViewSet)
router.register(r'monitoring-layer-lithogenic-variegates', MonitoringLayerLithogenicVariegatesViewSet)
router.register(r'monitoring-layer-redoximorphic-features', MonitoringLayerRedoximorphicFeaturesViewSet)
router.register(r'monitoring-layer-redoximorphic-colours', MonitoringLayerRedoximorphicColourViewSet)
router.register(r'monitoring-layer-coatings-bridges', MonitoringLayerCoatingsBridgesViewSet)
router.register(r'monitoring-layer-ribbonlike-accumulations', MonitoringLayerRibbonlikeAccumulationsViewSet)
router.register(r'monitoring-layer-carbonates', MonitoringLayerCarbonatesViewSet)
router.register(r'monitoring-layer-gypsum', MonitoringLayerGypsumViewSet)
router.register(r'monitoring-layer-secondary-silica', MonitoringLayerSecondarySilicaViewSet)
router.register(r'monitoring-layer-consistences', MonitoringLayerConsistenceViewSet)
router.register(r'monitoring-layer-permafrost-features', MonitoringLayerPermafrostFeaturesViewSet)
router.register(r'monitoring-layer-organic-carbon', MonitoringLayerOrganicCarbonViewSet)
router.register(r'monitoring-layer-roots', MonitoringLayerRootsViewSet)
router.register(r'monitoring-layer-animal-activities', MonitoringLayerAnimalActivityViewSet)
router.register(r'monitoring-layer-human-alterations', MonitoringLayerHumanAlterationsViewSet)
router.register(r'monitoring-layer-degree-decomposition', MonitoringLayerDegreeDecompositionViewSet)
router.register(r'monitoring-layer-non-matrix-pores', MonitoringLayerNonMatrixPoreViewSet)
router.register(r'monitoring-layer-structures', MonitoringLayerStructureViewSet)
router.register(r'monitoring-lab-data', MonitoringLabDataViewSet)
router.register(r'indicators', IndicatorViewSet)
router.register(r'requests', RequestViewSet)

 
urlpatterns = [
    path('', include(router.urls)),
]