[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "s4m_catalogue"
version = "5.dev"
description = "Soil Data Catalogue for Soil4Med"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "GPL-3.0-or-later" }
keywords = ["s4m", "soils4med", "geonode", "django"]

dependencies = [
    "GeoNode @ https://github.com/GeoNode/geonode/archive/refs/heads/master.zip",
    "cachetools",
    "pymemcache",
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "scipy",
    "dill",
    "openpyxl",
    "django-extensions"
]

[project.urls]
Homepage = "https://github.com/crs4/med_sis/"

[tool.setuptools]
include-package-data = true

# Correct package discovery layout
[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]

[tool.setuptools.package-data]
"*" = ["**/thesauri/*.rdf"]
